### PR TITLE
feat: add blockchain subdomain facet

### PR DESCRIPTION
**Pull request by crisog**
Link T-14959

### CODE REVIEW

**Review by kutoft — APPROVED** [review]
LGTM

**Comment by kutoft** [comment]
@adshmh @blockjoe any feedback on this before we merge this?

**Review by adshmh — APPROVED** [review]
LGTM

**Comment by blockjoe** [comment]
lgtm; really nice to be able to drop my mental model of `0021 -> eth-mainnet`

**Pull request merged**
